/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPersonendpointSessionTokenWrapper.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPersonendpointSessionTokenWrapper (0 custom class methods, 1 custom properties)

#import "GTLPersonendpointSessionTokenWrapper.h"

// ----------------------------------------------------------------------------
//
//   GTLPersonendpointSessionTokenWrapper
//

@implementation GTLPersonendpointSessionTokenWrapper
@dynamic sessionToken;
@end
