/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryPersonendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   personendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryPersonendpoint (8 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLPersonendpointDeviceInfo;
@class GTLPersonendpointPersonCardsListWrapper;
@class GTLPersonendpointPersonInfoWrapper;

@interface GTLQueryPersonendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *deviceinfo;
@property (copy) NSString *email;
@property (copy) NSString *password;
@property (copy) NSString *personinfowrapper;
@property (copy) NSString *sessionId;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryPersonendpoint object.

// Method: personendpoint.nativeLogin
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointSessionTokenWrapper.
+ (id)queryForNativeLoginWithObject:(GTLPersonendpointDeviceInfo *)object
                              email:(NSString *)email
                           password:(NSString *)password;

// Method: personendpoint.nativeLoginRPC
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointSessionTokenWrapper.
+ (id)queryForNativeLoginRPCWithEmail:(NSString *)email
                             password:(NSString *)password
                           deviceinfo:(NSString *)deviceinfo;

// Method: personendpoint.nativeSignup
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointSessionTokenWrapper.
+ (id)queryForNativeSignupWithObject:(GTLPersonendpointPersonInfoWrapper *)object;

// Method: personendpoint.nativeSignupRPC
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointSessionTokenWrapper.
+ (id)queryForNativeSignupRPCWithPersoninfowrapper:(NSString *)personinfowrapper;

// Method: personendpoint.replacePersonCards
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
+ (id)queryForReplacePersonCardsWithObject:(GTLPersonendpointPersonCardsListWrapper *)object
                                 sessionId:(NSString *)sessionId;

// Method: personendpoint.resetPassword
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
+ (id)queryForResetPasswordWithEmail:(NSString *)email;

// Method: personendpoint.socialSignup
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointSessionTokenWrapper.
+ (id)queryForSocialSignupWithObject:(GTLPersonendpointPersonInfoWrapper *)object;

// Method: personendpoint.socialSignupRPC
//  Authorization scope(s):
//   kGTLAuthScopePersonendpointUserinfoEmail
// Fetches a GTLPersonendpointSessionTokenWrapper.
+ (id)queryForSocialSignupRPCWithPersoninfowrapper:(NSString *)personinfowrapper;

@end
