/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryUserendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryUserendpoint (5 custom class methods, 2 custom properties)

#import "GTLQueryUserendpoint.h"

#import "GTLUserendpointUser.h"
#import "GTLUserendpointUserCard.h"
#import "GTLUserendpointUserCardCollection.h"

@implementation GTLQueryUserendpoint

@dynamic email, fields;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryUserendpoint object.

+ (id)queryForGetUserByEmailWithEmail:(NSString *)email {
  NSString *methodName = @"userendpoint.getUserByEmail";
  GTLQueryUserendpoint *query = [self queryWithMethodName:methodName];
  query.email = email;
  query.expectedObjectClass = [GTLUserendpointUser class];
  return query;
}

+ (id)queryForGetUserCards {
  NSString *methodName = @"userendpoint.getUserCards";
  GTLQueryUserendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLUserendpointUserCardCollection class];
  return query;
}

+ (id)queryForSaveUserWithObject:(GTLUserendpointUser *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userendpoint.saveUser";
  GTLQueryUserendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForSaveUserCardWithObject:(GTLUserendpointUserCard *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userendpoint.saveUserCard";
  GTLQueryUserendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserendpointUserCard class];
  return query;
}

+ (id)queryForSaveUserProfileWithObject:(GTLUserendpointUser *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userendpoint.saveUserProfile";
  GTLQueryUserendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserendpointUser class];
  return query;
}

@end
