/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreImageCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreImageCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreImageCollection.h"

#import "GTLStoreendpointStoreImage.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreImageCollection
//

@implementation GTLStoreendpointStoreImageCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreImage class]
                                forKey:@"items"];
  return map;
}

@end
