/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointOrderItem.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderItem (0 custom class methods, 14 custom properties)

#import "GTLStoreendpointOrderItem.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderItem
//

@implementation GTLStoreendpointOrderItem
@dynamic createdDate, descriptionProperty, finalPrice, identifier, initialPrice,
         menuItemId, menuItemName, modifiedDate, orderId, posOrderItemId,
         quantity, selectedOptions, specialInstructions, storeId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"description", @"descriptionProperty",
      @"id", @"identifier",
      nil];
  return map;
}

@end
