/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointOrder.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrder (0 custom class methods, 18 custom properties)

#import "GTLStoreendpointOrder.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrder
//

@implementation GTLStoreendpointOrder
@dynamic closeDate, createdDate, discount, discountDescription, gratuity,
         identifier, invoiceNumber, modifiedDate, paymentApprovalToken,
         paymentProvider, paymentType, posticket, serverId, serviceCharge,
         status, storeId, tax, totalAmount;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
