/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointOrderItem.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderItem (0 custom class methods, 14 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderItem
//

@interface GTLStoreendpointOrderItem : GTLObject
@property (retain) NSNumber *createdDate;  // longLongValue

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (copy) NSString *descriptionProperty;

@property (retain) NSNumber *finalPrice;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *initialPrice;  // longLongValue
@property (retain) NSNumber *menuItemId;  // longLongValue
@property (retain) NSNumber *menuItemName;  // longLongValue
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (retain) NSNumber *orderId;  // longLongValue
@property (retain) NSNumber *posOrderItemId;  // longLongValue
@property (retain) NSNumber *quantity;  // longLongValue
@property (copy) NSString *selectedOptions;
@property (copy) NSString *specialInstructions;
@property (retain) NSNumber *storeId;  // longLongValue
@end
