/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreSummaryStats.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreSummaryStats (0 custom class methods, 7 custom properties)

#import "GTLStoreendpointStoreSummaryStats.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreSummaryStats
//

@implementation GTLStoreendpointStoreSummaryStats
@dynamic createdDate, likes, modifiedDate, orders, recommendations, storeId,
         visits;
@end
