/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointOrderCustomer.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderCustomer (0 custom class methods, 6 custom properties)

#import "GTLStoreendpointOrderCustomer.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderCustomer
//

@implementation GTLStoreendpointOrderCustomer
@dynamic createdDate, identifier, modifiedDate, orderId, storeId, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
