/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreOwnerCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreOwnerCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreOwnerCollection.h"

#import "GTLStoreendpointStoreOwner.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreOwnerCollection
//

@implementation GTLStoreendpointStoreOwnerCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreOwner class]
                                forKey:@"items"];
  return map;
}

@end
