/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreCollection.h"

#import "GTLStoreendpointStore.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreCollection
//

@implementation GTLStoreendpointStoreCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStore class]
                                forKey:@"items"];
  return map;
}

@end
