/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointOrder.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrder (0 custom class methods, 20 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrder
//

@interface GTLStoreendpointOrder : GTLObject
@property (retain) NSNumber *closeDate;  // longLongValue
@property (retain) NSNumber *createdDate;  // longLongValue
@property (retain) NSNumber *discount;  // longLongValue
@property (copy) NSString *discountDescription;
@property (retain) NSNumber *gratuity;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *invoiceNumber;  // longLongValue
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (copy) NSString *paymentApprovalToken;
@property (copy) NSString *paymentProvider;
@property (copy) NSString *paymentType;
@property (retain) NSNumber *poscheckId;  // longLongValue
@property (copy) NSString *serverFirstName;
@property (copy) NSString *serverLastName;
@property (retain) NSNumber *serverPOSId;  // longLongValue
@property (retain) NSNumber *serviceCharge;  // longLongValue
@property (copy) NSString *status;
@property (retain) NSNumber *storeId;  // longLongValue
@property (retain) NSNumber *tax;  // longLongValue
@property (retain) NSNumber *totalAmount;  // longLongValue
@end
