/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreMenuItem.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreMenuItem (0 custom class methods, 26 custom properties)

#import "GTLStoreendpointStoreMenuItem.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreMenuItem
//

@implementation GTLStoreendpointStoreMenuItem
@dynamic active, allergyInfo, calories, createdDate, glutenFree, halal,
         hasModifiers, heatIndex, identifier, imageUrl, kosher, level,
         longDescription, menuItemPOSId, menuItemPosition, menuName, menuPOSId,
         modifiedDate, price, shortDescription, storeId, subMenuPOSId, tax,
         thumbnailUrl, vegan, vegetarian;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
