/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointOrderItemsAndCustomers.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderItemsAndCustomers (0 custom class methods, 3 custom properties)

#import "GTLStoreendpointOrderItemsAndCustomers.h"

#import "GTLStoreendpointOrder.h"
#import "GTLStoreendpointOrderCustomer.h"
#import "GTLStoreendpointOrderItem.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderItemsAndCustomers
//

@implementation GTLStoreendpointOrderItemsAndCustomers
@dynamic order, orderCustomers, orderItems;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLStoreendpointOrderCustomer class], @"orderCustomers",
      [GTLStoreendpointOrderItem class], @"orderItems",
      nil];
  return map;
}

@end
