/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreMenuHierarchyCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreMenuHierarchyCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreMenuHierarchyCollection.h"

#import "GTLStoreendpointStoreMenuHierarchy.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreMenuHierarchyCollection
//

@implementation GTLStoreendpointStoreMenuHierarchyCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreMenuHierarchy class]
                                forKey:@"items"];
  return map;
}

@end
