/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStore.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStore (0 custom class methods, 32 custom properties)

#import "GTLStoreendpointStore.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStore
//

@implementation GTLStoreendpointStore
@dynamic address, backgroundImageUrl, backgroundThumbnailUrl, beaconId, bssid,
         city, createdDate, deliveryDistance, descriptionProperty, fbUrl,
         gplusUrl, hours, identifier, isActive, lat, lng, modifiedDate, name,
         phone, priceRange, providesCarryout, providesDelivery,
         rewardsDescription, rewardsRate, ssid, state, subType, trophies,
         twitterUrl, type, webSiteUrl, zip;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"description", @"descriptionProperty",
      @"id", @"identifier",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSNumber class]
                                forKey:@"trophies"];
  return map;
}

@end
