/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointOrderItemsAndCustomers.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderItemsAndCustomers (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointOrder;
@class GTLStoreendpointOrderCustomer;
@class GTLStoreendpointOrderItem;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderItemsAndCustomers
//

@interface GTLStoreendpointOrderItemsAndCustomers : GTLObject
@property (retain) GTLStoreendpointOrder *order;
@property (retain) NSArray *orderCustomers;  // of GTLStoreendpointOrderCustomer
@property (retain) NSArray *orderItems;  // of GTLStoreendpointOrderItem
@end
