/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API

#import "GTLStoreendpointConstants.h"

#import "GTLStoreendpointMenuItemModifiersAndGroups.h"
#import "GTLStoreendpointMenusAndMenuItems.h"
#import "GTLStoreendpointStore.h"
#import "GTLStoreendpointStoreCollection.h"
#import "GTLStoreendpointStoreImage.h"
#import "GTLStoreendpointStoreImageCollection.h"
#import "GTLStoreendpointStoreMenuHierarchy.h"
#import "GTLStoreendpointStoreMenuHierarchyCollection.h"
#import "GTLStoreendpointStoreMenuItem.h"
#import "GTLStoreendpointStoreMenuItemCollection.h"
#import "GTLStoreendpointStoreMenuItemModifier.h"
#import "GTLStoreendpointStoreMenuItemModifierGroup.h"
#import "GTLStoreendpointStoreOrder.h"
#import "GTLStoreendpointStoreOwner.h"
#import "GTLStoreendpointStoreOwnerCollection.h"
#import "GTLStoreendpointStorePOSConnection.h"
#import "GTLStoreendpointStoreSummaryStats.h"
#import "GTLStoreendpointStoreSummaryStatsCollection.h"

#import "GTLQueryStoreendpoint.h"
#import "GTLServiceStoreendpoint.h"
