/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API

#import "GTLStoreendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeStoreendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
