/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryStoreendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryStoreendpoint (65 custom class methods, 18 custom properties)

#import "GTLQueryStoreendpoint.h"

#import "GTLStoreendpointAsaanLong.h"
#import "GTLStoreendpointAsaanLongCollection.h"
#import "GTLStoreendpointAsaanLongString.h"
#import "GTLStoreendpointChatMessage.h"
#import "GTLStoreendpointChatMessagesAndUsers.h"
#import "GTLStoreendpointChatRoom.h"
#import "GTLStoreendpointChatRoomsAndStoreChatMemberships.h"
#import "GTLStoreendpointChatUserArray.h"
#import "GTLStoreendpointClientVersionMatch.h"
#import "GTLStoreendpointItemReviewsArray.h"
#import "GTLStoreendpointMenuItemAndStatsCollection.h"
#import "GTLStoreendpointMenuItemModifiersAndGroups.h"
#import "GTLStoreendpointMenusAndMenuItems.h"
#import "GTLStoreendpointOrderAndReviews.h"
#import "GTLStoreendpointOrderReview.h"
#import "GTLStoreendpointOrderReviewAndItemReviews.h"
#import "GTLStoreendpointOrderReviewListAndCount.h"
#import "GTLStoreendpointPlaceOrderArguments.h"
#import "GTLStoreendpointSplitOrderArguments.h"
#import "GTLStoreendpointStore.h"
#import "GTLStoreendpointStoreAndStatsCollection.h"
#import "GTLStoreendpointStoreChatMemberArray.h"
#import "GTLStoreendpointStoreChatTeamCollection.h"
#import "GTLStoreendpointStoreCollection.h"
#import "GTLStoreendpointStoreDiscount.h"
#import "GTLStoreendpointStoreDiscountArray.h"
#import "GTLStoreendpointStoreDiscountCollection.h"
#import "GTLStoreendpointStoreMenuCombined.h"
#import "GTLStoreendpointStoreMenuHierarchy.h"
#import "GTLStoreendpointStoreMenuHierarchyCollection.h"
#import "GTLStoreendpointStoreMenuItem.h"
#import "GTLStoreendpointStoreMenuItemCollection.h"
#import "GTLStoreendpointStoreMenuItemModifier.h"
#import "GTLStoreendpointStoreMenuItemModifierGroup.h"
#import "GTLStoreendpointStoreOrder.h"
#import "GTLStoreendpointStoreOrderListAndCount.h"
#import "GTLStoreendpointStoreOwner.h"
#import "GTLStoreendpointStoreOwnerCollection.h"
#import "GTLStoreendpointStorePOSConnection.h"
#import "GTLStoreendpointStoreStats.h"
#import "GTLStoreendpointStoreStatsCollection.h"
#import "GTLStoreendpointStoreTableGroupCollection.h"
#import "GTLStoreendpointStoreTableGroupMember.h"
#import "GTLStoreendpointStoreTableGroupMemberArray.h"
#import "GTLStoreendpointStoreTableGroupMemberCollection.h"
#import "GTLStoreendpointStoreWaitListQueue.h"
#import "GTLStoreendpointStoreWaitListQueueAndPosition.h"
#import "GTLStoreendpointStoreWaitListQueueCollection.h"
#import "GTLStoreendpointStoreWaitlistSummary.h"
#import "GTLStoreendpointTableGroupsAndOrders.h"

@implementation GTLQueryStoreendpoint

@dynamic beaconId, fields, firstPosition, isStore, lat, lng, maxResult,
         menuItemPOSId, menuPOSId, menuType, modifiedDate, orderId,
         queuePosition, roomId, roomOrStoreId, storeId, storeName,
         storeTableGroupId;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryStoreendpoint object.

+ (id)queryForAddMemberToStoreTableGroupWithOrderId:(long long)orderId
                                  storeTableGroupId:(long long)storeTableGroupId {
  NSString *methodName = @"storeendpoint.addMemberToStoreTableGroup";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.orderId = orderId;
  query.storeTableGroupId = storeTableGroupId;
  return query;
}

+ (id)queryForCreateStoreTableGroupWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.createStoreTableGroup";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  return query;
}

+ (id)queryForGetChatMessagesForStoreOrRoomWithFirstPosition:(NSInteger)firstPosition
                                                     isStore:(BOOL)isStore
                                                   maxResult:(NSInteger)maxResult
                                                modifiedDate:(long long)modifiedDate
                                               roomOrStoreId:(long long)roomOrStoreId {
  NSString *methodName = @"storeendpoint.getChatMessagesForStoreOrRoom";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.isStore = isStore;
  query.maxResult = maxResult;
  query.modifiedDate = modifiedDate;
  query.roomOrStoreId = roomOrStoreId;
  query.expectedObjectClass = [GTLStoreendpointChatMessagesAndUsers class];
  return query;
}

+ (id)queryForGetChatRoomsAndMembershipsForUser {
  NSString *methodName = @"storeendpoint.getChatRoomsAndMembershipsForUser";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointChatRoomsAndStoreChatMemberships class];
  return query;
}

+ (id)queryForGetChatUsersForRoomWithRoomId:(long long)roomId {
  NSString *methodName = @"storeendpoint.getChatUsersForRoom";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.roomId = roomId;
  query.expectedObjectClass = [GTLStoreendpointChatUserArray class];
  return query;
}

+ (id)queryForGetClientVersion {
  NSString *methodName = @"storeendpoint.getClientVersion";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointClientVersionMatch class];
  return query;
}

+ (id)queryForGetMembersForStoreTableGroupWithStoreTableGroupId:(long long)storeTableGroupId {
  NSString *methodName = @"storeendpoint.getMembersForStoreTableGroup";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeTableGroupId = storeTableGroupId;
  query.expectedObjectClass = [GTLStoreendpointStoreTableGroupMemberCollection class];
  return query;
}

+ (id)queryForGetMenuItemAndStatsForMenuWithFirstPosition:(NSInteger)firstPosition
                                                maxResult:(NSInteger)maxResult
                                                menuPOSId:(NSInteger)menuPOSId
                                                  storeId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getMenuItemAndStatsForMenu";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.menuPOSId = menuPOSId;
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointMenuItemAndStatsCollection class];
  return query;
}

+ (id)queryForGetOpenAndUnassignedGroupsForStoreWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getOpenAndUnassignedGroupsForStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreTableGroupCollection class];
  return query;
}

+ (id)queryForGetOpenGroupForMember {
  NSString *methodName = @"storeendpoint.getOpenGroupForMember";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointStoreTableGroupMember class];
  return query;
}

+ (id)queryForGetOrderAndReviewsByIdWithOrderId:(long long)orderId {
  NSString *methodName = @"storeendpoint.getOrderAndReviewsById";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.orderId = orderId;
  query.expectedObjectClass = [GTLStoreendpointOrderAndReviews class];
  return query;
}

+ (id)queryForGetOrderReviewsForStoreWithFirstPosition:(NSInteger)firstPosition
                                             maxResult:(NSInteger)maxResult
                                               storeId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getOrderReviewsForStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointOrderReviewListAndCount class];
  return query;
}

+ (id)queryForGetReviewForCurrentUserAndOrderWithOrderId:(long long)orderId {
  NSString *methodName = @"storeendpoint.getReviewForCurrentUserAndOrder";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.orderId = orderId;
  query.expectedObjectClass = [GTLStoreendpointOrderReviewAndItemReviews class];
  return query;
}

+ (id)queryForGetStatsForAllStoresWithFirstPosition:(NSInteger)firstPosition
                                          maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStatsForAllStores";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreStatsCollection class];
  return query;
}

+ (id)queryForGetStoreWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStore class];
  return query;
}

+ (id)queryForGetStoreByBeaconIdWithBeaconId:(long long)beaconId {
  NSString *methodName = @"storeendpoint.getStoreByBeaconId";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.beaconId = beaconId;
  query.expectedObjectClass = [GTLStoreendpointStore class];
  return query;
}

+ (id)queryForGetStoreChatMembersWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreChatMembers";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreChatTeamCollection class];
  return query;
}

+ (id)queryForGetStoreChatTeamsForUser {
  NSString *methodName = @"storeendpoint.getStoreChatTeamsForUser";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointStoreChatTeamCollection class];
  return query;
}

+ (id)queryForGetStoreCount {
  NSString *methodName = @"storeendpoint.getStoreCount";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointAsaanLong class];
  return query;
}

+ (id)queryForGetStoreDiscountsWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreDiscounts";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreDiscountCollection class];
  return query;
}

+ (id)queryForGetStoreMenuHierarchyAndItemsWithMaxResult:(NSInteger)maxResult
                                                menuType:(NSInteger)menuType
                                                 storeId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreMenuHierarchyAndItems";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.maxResult = maxResult;
  query.menuType = menuType;
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointMenusAndMenuItems class];
  return query;
}

+ (id)queryForGetStoreMenuItemModifiersWithMenuItemPOSId:(NSInteger)menuItemPOSId
                                                 storeId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreMenuItemModifiers";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.menuItemPOSId = menuItemPOSId;
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointMenuItemModifiersAndGroups class];
  return query;
}

+ (id)queryForGetStoreMenuItemsWithFirstPosition:(NSInteger)firstPosition
                                       maxResult:(NSInteger)maxResult
                                         storeId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreMenuItems";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuItemCollection class];
  return query;
}

+ (id)queryForGetStoreMenusWithFirstPosition:(NSInteger)firstPosition
                                   maxResult:(NSInteger)maxResult
                                     storeId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreMenus";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuHierarchyCollection class];
  return query;
}

+ (id)queryForGetStoreOrderByIdWithOrderId:(long long)orderId {
  NSString *methodName = @"storeendpoint.getStoreOrderById";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.orderId = orderId;
  query.expectedObjectClass = [GTLStoreendpointStoreOrder class];
  return query;
}

+ (id)queryForGetStoreOrdersAndGroupsForEmployeeWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreOrdersAndGroupsForEmployee";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointTableGroupsAndOrders class];
  return query;
}

+ (id)queryForGetStoreOrdersForCurrentUserWithFirstPosition:(NSInteger)firstPosition
                                                  maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoreOrdersForCurrentUser";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreOrderListAndCount class];
  return query;
}

+ (id)queryForGetStoreOrdersForCurrentUserAndStoreWithFirstPosition:(NSInteger)firstPosition
                                                          maxResult:(NSInteger)maxResult
                                                            storeId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreOrdersForCurrentUserAndStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreOrderListAndCount class];
  return query;
}

+ (id)queryForGetStoreOwnersWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreOwners";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreOwnerCollection class];
  return query;
}

+ (id)queryForGetStorePOSConnectionWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStorePOSConnection";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStorePOSConnection class];
  return query;
}

+ (id)queryForGetStoresWithFirstPosition:(NSInteger)firstPosition
                               maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStores";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreCollection class];
  return query;
}

+ (id)queryForGetStoresOrderedByDistanceWithStatsWithFirstPosition:(NSInteger)firstPosition
                                                               lat:(double)lat
                                                               lng:(double)lng
                                                         maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoresOrderedByDistanceWithStats";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.lat = lat;
  query.lng = lng;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreAndStatsCollection class];
  return query;
}

+ (id)queryForGetStoresOrderedByDistanceWithStatsByOwnerWithFirstPosition:(NSInteger)firstPosition
                                                                      lat:(double)lat
                                                                      lng:(double)lng
                                                                maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoresOrderedByDistanceWithStatsByOwner";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.lat = lat;
  query.lng = lng;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreAndStatsCollection class];
  return query;
}

+ (id)queryForGetStoresOwnedByUser {
  NSString *methodName = @"storeendpoint.getStoresOwnedByUser";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointAsaanLongCollection class];
  return query;
}

+ (id)queryForGetStoreStatsWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreStats";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreStats class];
  return query;
}

+ (id)queryForGetStoresWithStatsWithFirstPosition:(NSInteger)firstPosition
                                        maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoresWithStats";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreAndStatsCollection class];
  return query;
}

+ (id)queryForGetStoreTableGroupsForStoreWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreTableGroupsForStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreTableGroupCollection class];
  return query;
}

+ (id)queryForGetStoreWaitListQueueWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreWaitListQueue";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreWaitListQueueCollection class];
  return query;
}

+ (id)queryForGetStoreWaitListQueueEntryForCurrentUser {
  NSString *methodName = @"storeendpoint.getStoreWaitListQueueEntryForCurrentUser";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointStoreWaitListQueueAndPosition class];
  return query;
}

+ (id)queryForPayForMemberWithObject:(GTLStoreendpointSplitOrderArguments *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.payForMember";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForPlaceOrderWithObject:(GTLStoreendpointPlaceOrderArguments *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.placeOrder";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreOrder class];
  return query;
}

+ (id)queryForRemoveStoreOwnerWithObject:(GTLStoreendpointStoreOwner *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.removeStoreOwner";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForReplaceStoreChatGroupWithObject:(GTLStoreendpointStoreChatMemberArray *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.replaceStoreChatGroup";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForReplaceStoreDiscountsWithObject:(GTLStoreendpointStoreDiscountArray *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.replaceStoreDiscounts";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForSaveChatMessageWithObject:(GTLStoreendpointChatMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveChatMessage";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointChatMessage class];
  return query;
}

+ (id)queryForSaveChatRoomWithObject:(GTLStoreendpointChatRoom *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveChatRoom";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointChatRoom class];
  return query;
}

+ (id)queryForSaveOrUpdateOrdersFromPOSWithObject:(GTLStoreendpointAsaanLongString *)object
                                          storeId:(long long)storeId
                                        storeName:(NSString *)storeName {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveOrUpdateOrdersFromPOS";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.storeId = storeId;
  query.storeName = storeName;
  return query;
}

+ (id)queryForSaveStoreWithObject:(GTLStoreendpointStore *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStore class];
  return query;
}

+ (id)queryForSaveStoreDiscountWithObject:(GTLStoreendpointStoreDiscount *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreDiscount";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreDiscount class];
  return query;
}

+ (id)queryForSaveStoreItemReviewsWithObject:(GTLStoreendpointItemReviewsArray *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreItemReviews";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForSaveStoreMenuCombinedWithObject:(GTLStoreendpointStoreMenuCombined *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuCombined";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForSaveStoreMenuHierarchyWithObject:(GTLStoreendpointStoreMenuHierarchy *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuHierarchy";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuHierarchy class];
  return query;
}

+ (id)queryForSaveStoreMenuItemWithObject:(GTLStoreendpointStoreMenuItem *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuItem";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuItem class];
  return query;
}

+ (id)queryForSaveStoreMenuItemModifierWithObject:(GTLStoreendpointStoreMenuItemModifier *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuItemModifier";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuItemModifier class];
  return query;
}

+ (id)queryForSaveStoreMenuItemModifierGroupWithObject:(GTLStoreendpointStoreMenuItemModifierGroup *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuItemModifierGroup";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuItemModifierGroup class];
  return query;
}

+ (id)queryForSaveStoreOrderReviewWithObject:(GTLStoreendpointOrderReview *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreOrderReview";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointOrderReview class];
  return query;
}

+ (id)queryForSaveStoreOwnerWithObject:(GTLStoreendpointStoreOwner *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreOwner";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreOwner class];
  return query;
}

+ (id)queryForSaveStorePOSConnectionWithObject:(GTLStoreendpointStorePOSConnection *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStorePOSConnection";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForSaveStoreWaitlistQueueEntryWithObject:(GTLStoreendpointStoreWaitListQueue *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreWaitlistQueueEntry";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreWaitListQueue class];
  return query;
}

+ (id)queryForSaveStoreWaitlistQueueEntryByStoreEmployeeWithObject:(GTLStoreendpointStoreWaitListQueue *)object
                                                     queuePosition:(NSInteger)queuePosition {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreWaitlistQueueEntryByStoreEmployee";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.queuePosition = queuePosition;
  query.expectedObjectClass = [GTLStoreendpointStoreWaitListQueue class];
  return query;
}

+ (id)queryForSaveStoreWaitlistSummaryWithObject:(GTLStoreendpointStoreWaitlistSummary *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreWaitlistSummary";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForUpdateOrderFromServerWithObject:(GTLStoreendpointStoreOrder *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.updateOrderFromServer";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreOrder class];
  return query;
}

+ (id)queryForUpdateStoreCoordinates {
  NSString *methodName = @"storeendpoint.updateStoreCoordinates";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  return query;
}

+ (id)queryForUpdateStoreTableGroupWithOrderId:(long long)orderId
                             storeTableGroupId:(long long)storeTableGroupId {
  NSString *methodName = @"storeendpoint.updateStoreTableGroup";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.orderId = orderId;
  query.storeTableGroupId = storeTableGroupId;
  return query;
}

+ (id)queryForUpdateStoreTableGroupMemberWithObject:(GTLStoreendpointStoreTableGroupMemberArray *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.updateStoreTableGroupMember";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

@end
