/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointMenuItemAndStats.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointMenuItemAndStats (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointMenuItemAndStats.h"

#import "GTLStoreendpointStoreItemStats.h"
#import "GTLStoreendpointStoreMenuItem.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointMenuItemAndStats
//

@implementation GTLStoreendpointMenuItemAndStats
@dynamic menuItem, stats;
@end
