/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointItemReviewsArray.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointItemReviewsArray (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointItemReview;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointItemReviewsArray
//

@interface GTLStoreendpointItemReviewsArray : GTLObject
@property (retain) NSArray *itemReviews;  // of GTLStoreendpointItemReview
@end
