/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreItemStats.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreItemStats (0 custom class methods, 7 custom properties)

#import "GTLStoreendpointStoreItemStats.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreItemStats
//

@implementation GTLStoreendpointStoreItemStats
@dynamic dislikes, identifier, likes, menuItemPOSId, orders, recommends,
         storeId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
