/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreOrderListAndCount.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreOrderListAndCount (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointStoreOrderListAndCount.h"

#import "GTLStoreendpointStoreOrder.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreOrderListAndCount
//

@implementation GTLStoreendpointStoreOrderListAndCount
@dynamic count, orders;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreOrder class]
                                forKey:@"orders"];
  return map;
}

@end
