/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreChatTeam.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreChatTeam (0 custom class methods, 6 custom properties)

#import "GTLStoreendpointStoreChatTeam.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreChatTeam
//

@implementation GTLStoreendpointStoreChatTeam
@dynamic createdDate, identifier, modifiedDate, storeId, storeName, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
