/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointOrderReview.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderReview (0 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderReview
//

@interface GTLStoreendpointOrderReview : GTLObject
@property (copy) NSString *comments;
@property (retain) NSNumber *createdDate;  // longLongValue
@property (retain) NSNumber *foodLike;  // intValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (retain) NSNumber *orderId;  // longLongValue
@property (retain) NSNumber *serviceLike;  // intValue
@property (retain) NSNumber *storeId;  // longLongValue
@property (retain) NSNumber *userId;  // longLongValue
@property (copy) NSString *userName;
@end
