/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreOrderAndTeamDetails.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreOrderAndTeamDetails (0 custom class methods, 5 custom properties)

#import "GTLStoreendpointStoreOrderAndTeamDetails.h"

#import "GTLStoreendpointStore.h"
#import "GTLStoreendpointStoreOrder.h"
#import "GTLStoreendpointStoreTableGroup.h"
#import "GTLStoreendpointStoreTableGroupMember.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreOrderAndTeamDetails
//

@implementation GTLStoreendpointStoreOrderAndTeamDetails
@dynamic memberMe, members, order, store, storeTableGroup;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreTableGroupMember class]
                                forKey:@"members"];
  return map;
}

@end
