/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointChatRoomsAndStoreChatMemberships.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointChatRoomsAndStoreChatMemberships (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointChatRoomsAndStoreChatMemberships.h"

#import "GTLStoreendpointChatRoom.h"
#import "GTLStoreendpointStoreChatTeam.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointChatRoomsAndStoreChatMemberships
//

@implementation GTLStoreendpointChatRoomsAndStoreChatMemberships
@dynamic chatRooms, storeChatMemberships;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLStoreendpointChatRoom class], @"chatRooms",
      [GTLStoreendpointStoreChatTeam class], @"storeChatMemberships",
      nil];
  return map;
}

@end
