/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointChatRoom.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointChatRoom (0 custom class methods, 6 custom properties)

#import "GTLStoreendpointChatRoom.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointChatRoom
//

@implementation GTLStoreendpointChatRoom
@dynamic createdDate, identifier, modifiedDate, name, storeId, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
