/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointSplitOrderArguments.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointSplitOrderArguments (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointStoreTableGroupMember;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointSplitOrderArguments
//

@interface GTLStoreendpointSplitOrderArguments : GTLObject
@property (copy) NSString *cardid;
@property (copy) NSString *customerId;
@property (retain) NSArray *stgms;  // of GTLStoreendpointStoreTableGroupMember
@property (copy) NSString *token;
@end
