/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointTableGroupsAndOrders.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointTableGroupsAndOrders (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointTableGroupsAndOrders.h"

#import "GTLStoreendpointStoreOrder.h"
#import "GTLStoreendpointStoreTableGroup.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointTableGroupsAndOrders
//

@implementation GTLStoreendpointTableGroupsAndOrders
@dynamic groups, orders;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLStoreendpointStoreTableGroup class], @"groups",
      [GTLStoreendpointStoreOrder class], @"orders",
      nil];
  return map;
}

@end
