/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointChatUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointChatUser (0 custom class methods, 5 custom properties)

#import "GTLStoreendpointChatUser.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointChatUser
//

@implementation GTLStoreendpointChatUser
@dynamic name, objectId, phone, profilePhotoUrl, userId;
@end
