/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreStats.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreStats (0 custom class methods, 12 custom properties)

#import "GTLStoreendpointStoreStats.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreStats
//

@implementation GTLStoreendpointStoreStats
@dynamic createdDate, daysOfService, foodDislikes, foodLikes,
         lastOrderPlacedDate, modifiedDate, orders, recommendations,
         serviceDislikes, serviceLikes, storeId, visits;
@end
