/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointItemReviewsArray.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointItemReviewsArray (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointItemReviewsArray.h"

#import "GTLStoreendpointItemReview.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointItemReviewsArray
//

@implementation GTLStoreendpointItemReviewsArray
@dynamic itemReviews;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointItemReview class]
                                forKey:@"itemReviews"];
  return map;
}

@end
