/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreWaitListQueue.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreWaitListQueue (0 custom class methods, 18 custom properties)

#import "GTLStoreendpointStoreWaitListQueue.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreWaitListQueue
//

@implementation GTLStoreendpointStoreWaitListQueue
@dynamic createdDate, dateNotifiedAcknowledged, dateNotifiedTableIsReady,
         entryFromInternet, estimateChangedByStore, estTimeMax, estTimeMin,
         identifier, modifiedDate, partySize, status, storeId, storeName,
         userId, userName, userObjectId, userPhone, userProfilePhotoUrl;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
