/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreAndStatsAndCount.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreAndStatsAndCount (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointStoreAndStats;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreAndStatsAndCount
//

@interface GTLStoreendpointStoreAndStatsAndCount : GTLObject
@property (retain) NSArray *storeAndStatsList;  // of GTLStoreendpointStoreAndStats
@property (retain) NSNumber *storeCount;  // longLongValue
@end
