/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreDiscount.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreDiscount (0 custom class methods, 10 custom properties)

#import "GTLStoreendpointStoreDiscount.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreDiscount
//

@implementation GTLStoreendpointStoreDiscount
@dynamic code, dates, daysOfWeek, identifier, percentOrAmount, posDiscountId,
         storeId, times, title, value;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
