/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API

#import "GTLStoreendpointConstants.m"

#import "GTLStoreendpointAsaanLong.m"
#import "GTLStoreendpointAsaanLongString.m"
#import "GTLStoreendpointChatMessage.m"
#import "GTLStoreendpointChatMessagesAndUsers.m"
#import "GTLStoreendpointChatRoom.m"
#import "GTLStoreendpointChatRoomsAndStoreChatMemberships.m"
#import "GTLStoreendpointChatUser.m"
#import "GTLStoreendpointChatUserArray.m"
#import "GTLStoreendpointItemReview.m"
#import "GTLStoreendpointItemReviewsArray.m"
#import "GTLStoreendpointMenuItemAndStats.m"
#import "GTLStoreendpointMenuItemAndStatsCollection.m"
#import "GTLStoreendpointMenuItemModifiersAndGroups.m"
#import "GTLStoreendpointMenusAndMenuItems.m"
#import "GTLStoreendpointOrderAndReviews.m"
#import "GTLStoreendpointOrderReview.m"
#import "GTLStoreendpointOrderReviewAndItemReviews.m"
#import "GTLStoreendpointOrderReviewListAndCount.m"
#import "GTLStoreendpointPlaceOrderArguments.m"
#import "GTLStoreendpointStore.m"
#import "GTLStoreendpointStoreAndStats.m"
#import "GTLStoreendpointStoreAndStatsCollection.m"
#import "GTLStoreendpointStoreChatMemberArray.m"
#import "GTLStoreendpointStoreChatTeam.m"
#import "GTLStoreendpointStoreChatTeamCollection.m"
#import "GTLStoreendpointStoreCollection.m"
#import "GTLStoreendpointStoreDiscount.m"
#import "GTLStoreendpointStoreDiscountArray.m"
#import "GTLStoreendpointStoreDiscountCollection.m"
#import "GTLStoreendpointStoreItemStats.m"
#import "GTLStoreendpointStoreMenuCombined.m"
#import "GTLStoreendpointStoreMenuHierarchy.m"
#import "GTLStoreendpointStoreMenuHierarchyCollection.m"
#import "GTLStoreendpointStoreMenuItem.m"
#import "GTLStoreendpointStoreMenuItemCollection.m"
#import "GTLStoreendpointStoreMenuItemModifier.m"
#import "GTLStoreendpointStoreMenuItemModifierGroup.m"
#import "GTLStoreendpointStoreMenuStats.m"
#import "GTLStoreendpointStoreOrder.m"
#import "GTLStoreendpointStoreOrderListAndCount.m"
#import "GTLStoreendpointStoreOwner.m"
#import "GTLStoreendpointStoreOwnerCollection.m"
#import "GTLStoreendpointStorePOSConnection.m"
#import "GTLStoreendpointStoreStats.m"
#import "GTLStoreendpointStoreStatsCollection.m"
#import "GTLStoreendpointStoreWaitListQueue.m"
#import "GTLStoreendpointStoreWaitListQueueAndPosition.m"
#import "GTLStoreendpointStoreWaitListQueueCollection.m"
#import "GTLStoreendpointStoreWaitlistSummary.m"

#import "GTLQueryStoreendpoint.m"
#import "GTLServiceStoreendpoint.m"
