/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreDiscountArray.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreDiscountArray (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreDiscountArray.h"

#import "GTLStoreendpointStoreDiscount.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreDiscountArray
//

@implementation GTLStoreendpointStoreDiscountArray
@dynamic storeDiscounts;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreDiscount class]
                                forKey:@"storeDiscounts"];
  return map;
}

@end
