/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreAndStatsCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreAndStatsCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreAndStatsCollection.h"

#import "GTLStoreendpointStoreAndStats.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreAndStatsCollection
//

@implementation GTLStoreendpointStoreAndStatsCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreAndStats class]
                                forKey:@"items"];
  return map;
}

@end
