/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreOrderListAndCount.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreOrderListAndCount (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointStoreOrder;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreOrderListAndCount
//

@interface GTLStoreendpointStoreOrderListAndCount : GTLObject
@property (retain) NSNumber *count;  // longLongValue
@property (retain) NSArray *orders;  // of GTLStoreendpointStoreOrder
@end
