/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointClientVersionMatch.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointClientVersionMatch (0 custom class methods, 4 custom properties)

#import "GTLStoreendpointClientVersionMatch.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointClientVersionMatch
//

@implementation GTLStoreendpointClientVersionMatch
@dynamic approvedAndroidClientVersion, approvedIOSClientVersion, identifier,
         serverVersion;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
