/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointChatMessagesAndUsers.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointChatMessagesAndUsers (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointChatMessagesAndUsers.h"

#import "GTLStoreendpointChatMessage.h"
#import "GTLStoreendpointChatUser.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointChatMessagesAndUsers
//

@implementation GTLStoreendpointChatMessagesAndUsers
@dynamic chatMessages, chatUsers;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLStoreendpointChatMessage class], @"chatMessages",
      [GTLStoreendpointChatUser class], @"chatUsers",
      nil];
  return map;
}

@end
