/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointAsaanLongCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointAsaanLongCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointAsaanLongCollection.h"

#import "GTLStoreendpointAsaanLong.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointAsaanLongCollection
//

@implementation GTLStoreendpointAsaanLongCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointAsaanLong class]
                                forKey:@"items"];
  return map;
}

@end
