/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreOrder.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreOrder (0 custom class methods, 29 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreOrder
//

@interface GTLStoreendpointStoreOrder : GTLObject
@property (retain) NSNumber *closeDate;  // longLongValue
@property (retain) NSNumber *createdDate;  // longLongValue
@property (retain) NSNumber *deliveryFee;  // longLongValue
@property (retain) NSNumber *discount;  // longLongValue
@property (copy) NSString *discountDescription;
@property (copy) NSString *employeeName;
@property (retain) NSNumber *employeePOSId;  // intValue
@property (retain) NSNumber *faxId;  // longLongValue
@property (retain) NSNumber *finalTotal;  // longLongValue
@property (retain) NSNumber *guestCount;  // intValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (copy) NSString *note;
@property (copy) NSString *orderDetails;
@property (copy) NSString *orderHTML;
@property (retain) NSNumber *orderMode;  // intValue
@property (retain) NSNumber *orderStatus;  // intValue
@property (retain) NSNumber *orderTotal;  // longLongValue
@property (copy) NSString *paymentChargeId;
@property (copy) NSString *paymentInvoice;
@property (copy) NSString *paymentReceiptNumber;
@property (retain) NSNumber *poscheckId;  // intValue
@property (retain) NSNumber *posintCheckId;  // longLongValue
@property (retain) NSNumber *serviceCharge;  // longLongValue
@property (retain) NSNumber *storeId;  // longLongValue
@property (copy) NSString *storeName;
@property (retain) NSNumber *subTotal;  // longLongValue
@property (retain) NSNumber *tableNumber;  // intValue
@property (retain) NSNumber *tax;  // longLongValue
@end
