/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreWaitlistSummary.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreWaitlistSummary (0 custom class methods, 9 custom properties)

#import "GTLStoreendpointStoreWaitlistSummary.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreWaitlistSummary
//

@implementation GTLStoreendpointStoreWaitlistSummary
@dynamic createdDate, modifiedDate, partiesOfSize12, partiesOfSize34,
         partiesOfSize5OrMore, storeId, waitTime12, waitTime34, waitTime5OrMore;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"partiesOfSize1_2", @"partiesOfSize12",
      @"partiesOfSize3_4", @"partiesOfSize34",
      @"waitTime1_2", @"waitTime12",
      @"waitTime3_4", @"waitTime34",
      nil];
  return map;
}

@end
