/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreOrder.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreOrder (0 custom class methods, 34 custom properties)

#import "GTLStoreendpointStoreOrder.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreOrder
//

@implementation GTLStoreendpointStoreOrder
@dynamic alreadyPaidSubtotal, closeDate, createdDate, deliveryFee, discount,
         discountDescription, employeeId, employeeName, employeePOSId, faxId,
         finalTotal, guestCount, identifier, modifiedDate, note, orderDetails,
         orderHTML, orderMode, orderStatus, orderTotal, parseObjectId,
         paymentChargeId, paymentInvoice, paymentReceiptNumber, poscheckId,
         posintCheckId, serviceCharge, storeId, storeName, storeTableGroupId,
         subTotal, tableNumber, tax, version;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
