/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreTableGroupMemberArray.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreTableGroupMemberArray (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointStoreTableGroupMember;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreTableGroupMemberArray
//

@interface GTLStoreendpointStoreTableGroupMemberArray : GTLObject
@property (retain) NSArray *members;  // of GTLStoreendpointStoreTableGroupMember
@end
