/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointOrderAndReviews.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderAndReviews (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointOrderAndReviews.h"

#import "GTLStoreendpointOrderReviewAndItemReviews.h"
#import "GTLStoreendpointStoreOrder.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderAndReviews
//

@implementation GTLStoreendpointOrderAndReviews
@dynamic order, orderAndItemsReview;
@end
