/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointOrderReviewListAndCount.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderReviewListAndCount (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointOrderReviewListAndCount.h"

#import "GTLStoreendpointOrderReview.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderReviewListAndCount
//

@implementation GTLStoreendpointOrderReviewListAndCount
@dynamic count, reviews;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointOrderReview class]
                                forKey:@"reviews"];
  return map;
}

@end
