/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStorePOSConnection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStorePOSConnection (0 custom class methods, 15 custom properties)

#import "GTLStoreendpointStorePOSConnection.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStorePOSConnection
//

@implementation GTLStoreendpointStorePOSConnection
@dynamic asaanTenderId, carryoutModeId, createdDate, deliveryModeId,
         dineInModeId, fallbackEmail, fallbackFax, hiddenHeaderName,
         hiddenHeaderValue, modifiedDate, preOrderModeId, status, storeId,
         token, url;
@end
