/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreTableGroupMember.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreTableGroupMember (0 custom class methods, 22 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreTableGroupMember
//

@interface GTLStoreendpointStoreTableGroupMember : GTLObject
@property (retain) NSNumber *createdDate;  // longLongValue
@property (retain) NSNumber *finalTotal;  // longLongValue
@property (copy) NSString *firstName;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *lastName;
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (retain) NSNumber *orderId;  // longLongValue
@property (copy) NSString *paidItems;
@property (copy) NSString *parseObjectId;
@property (retain) NSNumber *payingFor;  // intValue
@property (retain) NSNumber *payingUserId;  // longLongValue
@property (copy) NSString *paymentChargeId;
@property (copy) NSString *paymentInvoice;
@property (copy) NSString *paymentReceiptNumber;
@property (retain) NSNumber *paymentType;  // intValue
@property (copy) NSString *profilePhotoUrl;
@property (retain) NSNumber *status;  // intValue
@property (retain) NSNumber *storeTableGroupId;  // longLongValue
@property (retain) NSNumber *subtotal;  // longLongValue
@property (retain) NSNumber *tax;  // longLongValue
@property (retain) NSNumber *tip;  // longLongValue
@property (retain) NSNumber *userId;  // longLongValue
@end
