/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointPlaceOrderArguments.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointPlaceOrderArguments (0 custom class methods, 6 custom properties)

#import "GTLStoreendpointPlaceOrderArguments.h"

#import "GTLStoreendpointStoreOrder.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointPlaceOrderArguments
//

@implementation GTLStoreendpointPlaceOrderArguments
@dynamic cardid, customerId, order, strOrder, token, userId;
@end
