/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreTableGroup.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreTableGroup (0 custom class methods, 10 custom properties)

#import "GTLStoreendpointStoreTableGroup.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreTableGroup
//

@implementation GTLStoreendpointStoreTableGroup
@dynamic createdDate, firstName, identifier, lastName, modifiedDate, orderId,
         profilePhotoUrl, status, storeId, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
