/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreMenuItemCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreMenuItemCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreMenuItemCollection.h"

#import "GTLStoreendpointStoreMenuItem.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreMenuItemCollection
//

@implementation GTLStoreendpointStoreMenuItemCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreMenuItem class]
                                forKey:@"items"];
  return map;
}

@end
