/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointPlaceOrderArguments.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointPlaceOrderArguments (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointStoreOrder;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointPlaceOrderArguments
//

@interface GTLStoreendpointPlaceOrderArguments : GTLObject
@property (copy) NSString *cardid;
@property (copy) NSString *customerId;
@property (retain) GTLStoreendpointStoreOrder *order;
@property (copy) NSString *strOrder;
@property (copy) NSString *token;
@property (retain) NSNumber *userId;  // longLongValue
@end
