/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreAndStatsAndCount.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreAndStatsAndCount (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointStoreAndStatsAndCount.h"

#import "GTLStoreendpointStoreAndStats.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreAndStatsAndCount
//

@implementation GTLStoreendpointStoreAndStatsAndCount
@dynamic storeAndStatsList, storeCount;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreAndStats class]
                                forKey:@"storeAndStatsList"];
  return map;
}

@end
