/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreTableGroup.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreTableGroup (0 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreTableGroup
//

@interface GTLStoreendpointStoreTableGroup : GTLObject
@property (retain) NSNumber *createdDate;  // longLongValue
@property (copy) NSString *firstName;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *lastName;
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (retain) NSNumber *orderId;  // longLongValue
@property (copy) NSString *profilePhotoUrl;
@property (retain) NSNumber *status;  // intValue
@property (retain) NSNumber *storeId;  // longLongValue
@property (retain) NSNumber *userId;  // longLongValue
@end
