/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointChatMessagesAndUsers.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointChatMessagesAndUsers (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointChatMessage;
@class GTLStoreendpointChatUser;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointChatMessagesAndUsers
//

@interface GTLStoreendpointChatMessagesAndUsers : GTLObject
@property (retain) NSArray *chatMessages;  // of GTLStoreendpointChatMessage
@property (retain) NSArray *chatUsers;  // of GTLStoreendpointChatUser
@end
