/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreOwner.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreOwner (0 custom class methods, 5 custom properties)

#import "GTLStoreendpointStoreOwner.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreOwner
//

@implementation GTLStoreendpointStoreOwner
@dynamic createdDate, identifier, modifiedDate, storeId, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
