/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreTableGroupCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreTableGroupCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreTableGroupCollection.h"

#import "GTLStoreendpointStoreTableGroup.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreTableGroupCollection
//

@implementation GTLStoreendpointStoreTableGroupCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreTableGroup class]
                                forKey:@"items"];
  return map;
}

@end
