/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserendpointChatUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointChatUser (0 custom class methods, 5 custom properties)

#import "GTLUserendpointChatUser.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointChatUser
//

@implementation GTLUserendpointChatUser
@dynamic name, objectId, phone, profilePhotoUrl, userId;
@end
