/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserendpointChatUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointChatUser (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUserendpointChatUser
//

@interface GTLUserendpointChatUser : GTLObject
@property (copy) NSString *name;
@property (copy) NSString *objectId;
@property (copy) NSString *phone;
@property (copy) NSString *profilePhotoUrl;
@property (retain) NSNumber *userId;  // longLongValue
@end
