/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API

#import "GTLUserendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeUserendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
