/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryStoreendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryStoreendpoint (31 custom class methods, 12 custom properties)

#import "GTLQueryStoreendpoint.h"

#import "GTLStoreendpointAsaanLong.h"
#import "GTLStoreendpointAsaanLongString.h"
#import "GTLStoreendpointGetCheckDetailsPOSResponse.h"
#import "GTLStoreendpointMenuItemAndStatsCollection.h"
#import "GTLStoreendpointMenuItemModifiersAndGroups.h"
#import "GTLStoreendpointMenusAndMenuItems.h"
#import "GTLStoreendpointOrderReviewAndItemReviews.h"
#import "GTLStoreendpointStore.h"
#import "GTLStoreendpointStoreAndStatsCollection.h"
#import "GTLStoreendpointStoreCollection.h"
#import "GTLStoreendpointStoreDiscount.h"
#import "GTLStoreendpointStoreDiscountArray.h"
#import "GTLStoreendpointStoreDiscountCollection.h"
#import "GTLStoreendpointStoreMenuCombined.h"
#import "GTLStoreendpointStoreMenuHierarchy.h"
#import "GTLStoreendpointStoreMenuHierarchyCollection.h"
#import "GTLStoreendpointStoreMenuItem.h"
#import "GTLStoreendpointStoreMenuItemCollection.h"
#import "GTLStoreendpointStoreMenuItemModifier.h"
#import "GTLStoreendpointStoreMenuItemModifierGroup.h"
#import "GTLStoreendpointStoreOrder.h"
#import "GTLStoreendpointStoreOrderListAndCount.h"
#import "GTLStoreendpointStoreOwner.h"
#import "GTLStoreendpointStoreOwnerCollection.h"
#import "GTLStoreendpointStorePOSConnection.h"
#import "GTLStoreendpointStoreStats.h"
#import "GTLStoreendpointStoreStatsCollection.h"

@implementation GTLQueryStoreendpoint

@dynamic fields, firstPosition, guestCount, maxResult, menuItemPOSId, menuPOSId,
         menuType, orderId, orderMode, storeId, storeName, userId;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryStoreendpoint object.

+ (id)queryForGetCheckDetailsPOSResponseEmptyObject {
  NSString *methodName = @"storeendpoint.getCheckDetailsPOSResponseEmptyObject";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointGetCheckDetailsPOSResponse class];
  return query;
}

+ (id)queryForGetMenuItemAndStatsForMenuWithStoreId:(long long)storeId
                                          menuPOSId:(NSInteger)menuPOSId
                                      firstPosition:(NSInteger)firstPosition
                                          maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getMenuItemAndStatsForMenu";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.menuPOSId = menuPOSId;
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointMenuItemAndStatsCollection class];
  return query;
}

+ (id)queryForGetReviewsForUserAndOrderWithUserId:(long long)userId
                                          orderId:(long long)orderId {
  NSString *methodName = @"storeendpoint.getReviewsForUserAndOrder";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.userId = userId;
  query.orderId = orderId;
  query.expectedObjectClass = [GTLStoreendpointOrderReviewAndItemReviews class];
  return query;
}

+ (id)queryForGetStatsForAllStoresWithFirstPosition:(NSInteger)firstPosition
                                          maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStatsForAllStores";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreStatsCollection class];
  return query;
}

+ (id)queryForGetStoreWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStore class];
  return query;
}

+ (id)queryForGetStoreCount {
  NSString *methodName = @"storeendpoint.getStoreCount";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLStoreendpointAsaanLong class];
  return query;
}

+ (id)queryForGetStoreDiscountsWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreDiscounts";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreDiscountCollection class];
  return query;
}

+ (id)queryForGetStoreMenuHierarchyAndItemsWithStoreId:(long long)storeId
                                              menuType:(NSInteger)menuType
                                             maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoreMenuHierarchyAndItems";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.menuType = menuType;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointMenusAndMenuItems class];
  return query;
}

+ (id)queryForGetStoreMenuItemModifiersWithStoreId:(long long)storeId
                                     menuItemPOSId:(NSInteger)menuItemPOSId {
  NSString *methodName = @"storeendpoint.getStoreMenuItemModifiers";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.menuItemPOSId = menuItemPOSId;
  query.expectedObjectClass = [GTLStoreendpointMenuItemModifiersAndGroups class];
  return query;
}

+ (id)queryForGetStoreMenuItemsWithStoreId:(long long)storeId
                             firstPosition:(NSInteger)firstPosition
                                 maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoreMenuItems";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuItemCollection class];
  return query;
}

+ (id)queryForGetStoreMenusWithStoreId:(long long)storeId
                         firstPosition:(NSInteger)firstPosition
                             maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoreMenus";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuHierarchyCollection class];
  return query;
}

+ (id)queryForGetStoreOrdersByUserWithFirstPosition:(NSInteger)firstPosition
                                          maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoreOrdersByUser";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreOrderListAndCount class];
  return query;
}

+ (id)queryForGetStoreOrdersByUserAndStoreWithStoreId:(long long)storeId
                                        firstPosition:(NSInteger)firstPosition
                                            maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoreOrdersByUserAndStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreOrderListAndCount class];
  return query;
}

+ (id)queryForGetStoreOwnersWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreOwners";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreOwnerCollection class];
  return query;
}

+ (id)queryForGetStorePOSConnectionWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStorePOSConnection";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStorePOSConnection class];
  return query;
}

+ (id)queryForGetStoresWithFirstPosition:(NSInteger)firstPosition
                               maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStores";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreCollection class];
  return query;
}

+ (id)queryForGetStoreStatsWithStoreId:(long long)storeId {
  NSString *methodName = @"storeendpoint.getStoreStats";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.storeId = storeId;
  query.expectedObjectClass = [GTLStoreendpointStoreStats class];
  return query;
}

+ (id)queryForGetStoresWithStatsWithFirstPosition:(NSInteger)firstPosition
                                        maxResult:(NSInteger)maxResult {
  NSString *methodName = @"storeendpoint.getStoresWithStats";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.firstPosition = firstPosition;
  query.maxResult = maxResult;
  query.expectedObjectClass = [GTLStoreendpointStoreAndStatsCollection class];
  return query;
}

+ (id)queryForPlaceOrderWithObject:(GTLStoreendpointAsaanLongString *)object
                           storeId:(long long)storeId
                         orderMode:(NSInteger)orderMode
                        guestCount:(NSInteger)guestCount
                         storeName:(NSString *)storeName {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.placeOrder";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.storeId = storeId;
  query.orderMode = orderMode;
  query.guestCount = guestCount;
  query.storeName = storeName;
  query.expectedObjectClass = [GTLStoreendpointStoreOrder class];
  return query;
}

+ (id)queryForRemoveStoreOwnerWithObject:(GTLStoreendpointStoreOwner *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.removeStoreOwner";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForReplaceStoreDiscountsWithObject:(GTLStoreendpointStoreDiscountArray *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.replaceStoreDiscounts";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForSaveOrUpdateOrdersFromPOSWithObject:(GTLStoreendpointAsaanLongString *)object
                                          storeId:(long long)storeId
                                        storeName:(NSString *)storeName {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveOrUpdateOrdersFromPOS";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.storeId = storeId;
  query.storeName = storeName;
  return query;
}

+ (id)queryForSaveStoreWithObject:(GTLStoreendpointStore *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStore";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStore class];
  return query;
}

+ (id)queryForSaveStoreDiscountWithObject:(GTLStoreendpointStoreDiscount *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreDiscount";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForSaveStoreMenuCombinedWithObject:(GTLStoreendpointStoreMenuCombined *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuCombined";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

+ (id)queryForSaveStoreMenuHierarchyWithObject:(GTLStoreendpointStoreMenuHierarchy *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuHierarchy";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuHierarchy class];
  return query;
}

+ (id)queryForSaveStoreMenuItemWithObject:(GTLStoreendpointStoreMenuItem *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuItem";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuItem class];
  return query;
}

+ (id)queryForSaveStoreMenuItemModifierWithObject:(GTLStoreendpointStoreMenuItemModifier *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuItemModifier";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuItemModifier class];
  return query;
}

+ (id)queryForSaveStoreMenuItemModifierGroupWithObject:(GTLStoreendpointStoreMenuItemModifierGroup *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreMenuItemModifierGroup";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreMenuItemModifierGroup class];
  return query;
}

+ (id)queryForSaveStoreOwnerWithObject:(GTLStoreendpointStoreOwner *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStoreOwner";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLStoreendpointStoreOwner class];
  return query;
}

+ (id)queryForSaveStorePOSConnectionWithObject:(GTLStoreendpointStorePOSConnection *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"storeendpoint.saveStorePOSConnection";
  GTLQueryStoreendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  return query;
}

@end
