/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointENTRY.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointENTRY (0 custom class methods, 9 custom properties)

#import "GTLStoreendpointENTRY.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointENTRY
//

@implementation GTLStoreendpointENTRY
@dynamic dispname, entrytype, identifier, itemid, ordermode, parententry, price,
         quantity, value;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
