/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreMenuStats.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreMenuStats (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreMenuStats
//

@interface GTLStoreendpointStoreMenuStats : GTLObject

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *menuPOSId;  // intValue
@property (retain) NSNumber *mostFrequentlyOrderedMenuItemPOSId;  // intValue
@property (retain) NSNumber *mostLikedMenuItemPOSId;  // intValue
@property (retain) NSNumber *mostRecommendedMenuItemPOSId;  // intValue
@property (retain) NSNumber *storeId;  // longLongValue
@property (retain) NSNumber *subMenuPOSId;  // intValue
@end
