/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreMenuHierarchy.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreMenuHierarchy (0 custom class methods, 13 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreMenuHierarchy
//

@interface GTLStoreendpointStoreMenuHierarchy : GTLObject
@property (retain) NSNumber *active;  // boolValue
@property (retain) NSNumber *createdDate;  // longLongValue
@property (copy) NSString *hours;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *level;  // intValue
@property (retain) NSNumber *menuItemCount;  // intValue
@property (retain) NSNumber *menuItemPosition;  // intValue
@property (retain) NSNumber *menuPOSId;  // intValue
@property (retain) NSNumber *menuType;  // intValue
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (copy) NSString *name;
@property (retain) NSNumber *storeId;  // longLongValue
@property (retain) NSNumber *subMenuPOSId;  // intValue
@end
