/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointMenuItemModifiersAndGroups.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointMenuItemModifiersAndGroups (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointMenuItemModifiersAndGroups.h"

#import "GTLStoreendpointStoreMenuItemModifier.h"
#import "GTLStoreendpointStoreMenuItemModifierGroup.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointMenuItemModifiersAndGroups
//

@implementation GTLStoreendpointMenuItemModifiersAndGroups
@dynamic modifierGroups, modifiers;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLStoreendpointStoreMenuItemModifierGroup class], @"modifierGroups",
      [GTLStoreendpointStoreMenuItemModifier class], @"modifiers",
      nil];
  return map;
}

@end
