/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreWaitListQueueAndPosition.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreWaitListQueueAndPosition (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointStoreWaitListQueueAndPosition.h"

#import "GTLStoreendpointStoreWaitListQueue.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreWaitListQueueAndPosition
//

@implementation GTLStoreendpointStoreWaitListQueueAndPosition
@dynamic partiesBeforeEntry, queueEntry;
@end
