/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreStats.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreStats (0 custom class methods, 10 custom properties)

#import "GTLStoreendpointStoreStats.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreStats
//

@implementation GTLStoreendpointStoreStats
@dynamic createdDate, daysOfService, dislikes, lastOrderPlacedDate, likes,
         modifiedDate, orders, recommendations, storeId, visits;
@end
