/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointGetCheckDetailsPOSResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointGetCheckDetailsPOSResponse (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointGetCheckDetailsPOSResponse.h"

#import "GTLStoreendpointGETCHECKDETAILS.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointGetCheckDetailsPOSResponse
//

@implementation GTLStoreendpointGetCheckDetailsPOSResponse
@dynamic getcheckdetails;
@end
