/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointMenuItemModifiersAndGroups.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointMenuItemModifiersAndGroups (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointStoreMenuItemModifier;
@class GTLStoreendpointStoreMenuItemModifierGroup;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointMenuItemModifiersAndGroups
//

@interface GTLStoreendpointMenuItemModifiersAndGroups : GTLObject
@property (retain) NSArray *modifierGroups;  // of GTLStoreendpointStoreMenuItemModifierGroup
@property (retain) NSArray *modifiers;  // of GTLStoreendpointStoreMenuItemModifier
@end
