/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreMenuCombined.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreMenuCombined (0 custom class methods, 5 custom properties)

#import "GTLStoreendpointStoreMenuCombined.h"

#import "GTLStoreendpointStoreMenuHierarchy.h"
#import "GTLStoreendpointStoreMenuItem.h"
#import "GTLStoreendpointStoreMenuItemModifier.h"
#import "GTLStoreendpointStoreMenuItemModifierGroup.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreMenuCombined
//

@implementation GTLStoreendpointStoreMenuCombined
@dynamic storeId, storeMenuHierarchy, storeMenuItem, storeMenuItemModifier,
         storeMenuItemModifierGroup;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      [GTLStoreendpointStoreMenuHierarchy class], @"storeMenuHierarchy",
      [GTLStoreendpointStoreMenuItem class], @"storeMenuItem",
      [GTLStoreendpointStoreMenuItemModifier class], @"storeMenuItemModifier",
      [GTLStoreendpointStoreMenuItemModifierGroup class], @"storeMenuItemModifierGroup",
      nil];
  return map;
}

@end
