/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStorePOSConnection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStorePOSConnection (0 custom class methods, 13 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStorePOSConnection
//

@interface GTLStoreendpointStorePOSConnection : GTLObject
@property (retain) NSNumber *asaanTenderId;  // intValue
@property (retain) NSNumber *carryoutModeId;  // intValue
@property (retain) NSNumber *createdDate;  // longLongValue
@property (retain) NSNumber *deliveryModeId;  // intValue
@property (copy) NSString *fallbackEmail;
@property (copy) NSString *fallbackFax;
@property (copy) NSString *hiddenHeaderName;
@property (copy) NSString *hiddenHeaderValue;
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (retain) NSNumber *status;  // longLongValue
@property (retain) NSNumber *storeId;  // longLongValue
@property (copy) NSString *token;
@property (copy) NSString *url;
@end
