/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointDISCOUNTS.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointDISCOUNTS (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointDISCOUNT;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointDISCOUNTS
//

@interface GTLStoreendpointDISCOUNTS : GTLObject
@property (retain) NSArray *discount;  // of GTLStoreendpointDISCOUNT
@end
