/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointMenusAndMenuItems.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointMenusAndMenuItems (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointMenuItemAndStats;
@class GTLStoreendpointStoreMenuHierarchy;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointMenusAndMenuItems
//

@interface GTLStoreendpointMenusAndMenuItems : GTLObject
@property (retain) NSArray *menuItems;  // of GTLStoreendpointMenuItemAndStats
@property (retain) NSArray *menusAndSubmenus;  // of GTLStoreendpointStoreMenuHierarchy
@end
