/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API

#import "GTLStoreendpointConstants.m"

#import "GTLStoreendpointAsaanLong.m"
#import "GTLStoreendpointAsaanLongString.m"
#import "GTLStoreendpointCHECK.m"
#import "GTLStoreendpointDISCOUNT.m"
#import "GTLStoreendpointDISCOUNTS.m"
#import "GTLStoreendpointENTRIES.m"
#import "GTLStoreendpointENTRY.m"
#import "GTLStoreendpointGETCHECKDETAILS.m"
#import "GTLStoreendpointGetCheckDetailsPOSResponse.m"
#import "GTLStoreendpointItemReview.m"
#import "GTLStoreendpointItemReviewsArray.m"
#import "GTLStoreendpointMenuItemAndStats.m"
#import "GTLStoreendpointMenuItemAndStatsCollection.m"
#import "GTLStoreendpointMenuItemModifiersAndGroups.m"
#import "GTLStoreendpointMenusAndMenuItems.m"
#import "GTLStoreendpointOrderReview.m"
#import "GTLStoreendpointOrderReviewAndItemReviews.m"
#import "GTLStoreendpointStore.m"
#import "GTLStoreendpointStoreAndStats.m"
#import "GTLStoreendpointStoreAndStatsCollection.m"
#import "GTLStoreendpointStoreCollection.m"
#import "GTLStoreendpointStoreDiscount.m"
#import "GTLStoreendpointStoreDiscountArray.m"
#import "GTLStoreendpointStoreDiscountCollection.m"
#import "GTLStoreendpointStoreItemStats.m"
#import "GTLStoreendpointStoreMenuCombined.m"
#import "GTLStoreendpointStoreMenuHierarchy.m"
#import "GTLStoreendpointStoreMenuHierarchyCollection.m"
#import "GTLStoreendpointStoreMenuItem.m"
#import "GTLStoreendpointStoreMenuItemCollection.m"
#import "GTLStoreendpointStoreMenuItemModifier.m"
#import "GTLStoreendpointStoreMenuItemModifierGroup.m"
#import "GTLStoreendpointStoreOrder.m"
#import "GTLStoreendpointStoreOrderListAndCount.m"
#import "GTLStoreendpointStoreOwner.m"
#import "GTLStoreendpointStoreOwnerCollection.m"
#import "GTLStoreendpointStorePOSConnection.m"
#import "GTLStoreendpointStoreStats.m"
#import "GTLStoreendpointStoreStatsCollection.m"

#import "GTLQueryStoreendpoint.m"
#import "GTLServiceStoreendpoint.m"
