/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointENTRIES.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointENTRIES (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointENTRY;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointENTRIES
//

@interface GTLStoreendpointENTRIES : GTLObject
@property (retain) NSArray *entry;  // of GTLStoreendpointENTRY
@end
