/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpoint_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API

#import "GTLStoreendpointConstants.m"

#import "GTLStoreendpointMenuItemModifiersAndGroups.m"
#import "GTLStoreendpointMenusAndMenuItems.m"
#import "GTLStoreendpointStore.m"
#import "GTLStoreendpointStoreCollection.m"
#import "GTLStoreendpointStoreMenuCombined.m"
#import "GTLStoreendpointStoreMenuHierarchy.m"
#import "GTLStoreendpointStoreMenuHierarchyCollection.m"
#import "GTLStoreendpointStoreMenuItem.m"
#import "GTLStoreendpointStoreMenuItemCollection.m"
#import "GTLStoreendpointStoreMenuItemModifier.m"
#import "GTLStoreendpointStoreMenuItemModifierGroup.m"
#import "GTLStoreendpointStoreOrder.m"
#import "GTLStoreendpointStoreOwner.m"
#import "GTLStoreendpointStoreOwnerCollection.m"
#import "GTLStoreendpointStorePOSConnection.m"
#import "GTLStoreendpointStoreStats.m"
#import "GTLStoreendpointStoreStatsCollection.m"

#import "GTLQueryStoreendpoint.m"
#import "GTLServiceStoreendpoint.m"
