/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStore.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStore (0 custom class methods, 39 custom properties)

#import "GTLStoreendpointStore.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStore
//

@implementation GTLStoreendpointStore
@dynamic address, backgroundImageUrl, backgroundThumbnailUrl, beaconId, bssid,
         city, claimed, createdDate, deliveryDistance, deliveryFee,
         descriptionProperty, executiveChef, fbUrl, gplusUrl, hours, identifier,
         isActive, lat, lng, minOrderAmtForDelivery, modifiedDate, name, phone,
         priceRange, providesCarryout, providesDelivery, providesPreOrder,
         rewardsDescription, rewardsRate, ssid, state, subType, supportsChat,
         supportsReservation, trophies, twitterUrl, type, webSiteUrl, zip;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"description", @"descriptionProperty",
      @"id", @"identifier",
      nil];
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[NSString class]
                                forKey:@"trophies"];
  return map;
}

@end
