/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreItemStats.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreItemStats (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreItemStats
//

@interface GTLStoreendpointStoreItemStats : GTLObject
@property (retain) NSNumber *dislikes;  // longLongValue

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *likes;  // longLongValue
@property (retain) NSNumber *menuItemPOSId;  // intValue
@property (retain) NSNumber *menuPOSId;  // intValue
@property (retain) NSNumber *mostFrequentlyOrdered;  // boolValue
@property (retain) NSNumber *orders;  // longLongValue
@property (retain) NSNumber *storeId;  // longLongValue
@property (retain) NSNumber *subMenuPOSId;  // intValue
@end
