/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreStatsCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreStatsCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreStatsCollection.h"

#import "GTLStoreendpointStoreStats.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreStatsCollection
//

@implementation GTLStoreendpointStoreStatsCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreStats class]
                                forKey:@"items"];
  return map;
}

@end
