/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointOrderReview.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderReview (0 custom class methods, 10 custom properties)

#import "GTLStoreendpointOrderReview.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderReview
//

@implementation GTLStoreendpointOrderReview
@dynamic comments, createdDate, foodLike, hasItemReviews, identifier,
         modifiedDate, orderId, serviceLike, storeId, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
