/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLStoreendpointStoreMenuCombined.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreMenuCombined (0 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLStoreendpointStoreMenuHierarchy;
@class GTLStoreendpointStoreMenuItem;
@class GTLStoreendpointStoreMenuItemModifier;
@class GTLStoreendpointStoreMenuItemModifierGroup;

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreMenuCombined
//

@interface GTLStoreendpointStoreMenuCombined : GTLObject
@property (retain) NSNumber *storeId;  // longLongValue
@property (retain) NSArray *storeMenuHierarchy;  // of GTLStoreendpointStoreMenuHierarchy
@property (retain) NSArray *storeMenuItem;  // of GTLStoreendpointStoreMenuItem
@property (retain) NSArray *storeMenuItemModifier;  // of GTLStoreendpointStoreMenuItemModifier
@property (retain) NSArray *storeMenuItemModifierGroup;  // of GTLStoreendpointStoreMenuItemModifierGroup
@end
