/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreWaitListQueueCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreWaitListQueueCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreWaitListQueueCollection.h"

#import "GTLStoreendpointStoreWaitListQueue.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreWaitListQueueCollection
//

@implementation GTLStoreendpointStoreWaitListQueueCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreWaitListQueue class]
                                forKey:@"items"];
  return map;
}

@end
