/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointOrderReviewAndItemReviews.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointOrderReviewAndItemReviews (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointOrderReviewAndItemReviews.h"

#import "GTLStoreendpointItemReview.h"
#import "GTLStoreendpointOrderReview.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointOrderReviewAndItemReviews
//

@implementation GTLStoreendpointOrderReviewAndItemReviews
@dynamic itemReviews, orderReview;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointItemReview class]
                                forKey:@"itemReviews"];
  return map;
}

@end
