/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API

#import "GTLStoreendpointConstants.h"

#import "GTLStoreendpointAsaanLong.h"
#import "GTLStoreendpointAsaanLongString.h"
#import "GTLStoreendpointMenuItemAndStats.h"
#import "GTLStoreendpointMenuItemAndStatsCollection.h"
#import "GTLStoreendpointMenuItemModifiersAndGroups.h"
#import "GTLStoreendpointMenusAndMenuItems.h"
#import "GTLStoreendpointStore.h"
#import "GTLStoreendpointStoreAndStats.h"
#import "GTLStoreendpointStoreAndStatsCollection.h"
#import "GTLStoreendpointStoreCollection.h"
#import "GTLStoreendpointStoreDiscount.h"
#import "GTLStoreendpointStoreDiscountArray.h"
#import "GTLStoreendpointStoreDiscountCollection.h"
#import "GTLStoreendpointStoreItemStats.h"
#import "GTLStoreendpointStoreMenuCombined.h"
#import "GTLStoreendpointStoreMenuHierarchy.h"
#import "GTLStoreendpointStoreMenuHierarchyCollection.h"
#import "GTLStoreendpointStoreMenuItem.h"
#import "GTLStoreendpointStoreMenuItemCollection.h"
#import "GTLStoreendpointStoreMenuItemModifier.h"
#import "GTLStoreendpointStoreMenuItemModifierGroup.h"
#import "GTLStoreendpointStoreOrder.h"
#import "GTLStoreendpointStoreOwner.h"
#import "GTLStoreendpointStoreOwnerCollection.h"
#import "GTLStoreendpointStorePOSConnection.h"
#import "GTLStoreendpointStoreStats.h"
#import "GTLStoreendpointStoreStatsCollection.h"

#import "GTLQueryStoreendpoint.h"
#import "GTLServiceStoreendpoint.h"
