/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointDISCOUNT.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointDISCOUNT (0 custom class methods, 3 custom properties)

#import "GTLStoreendpointDISCOUNT.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointDISCOUNT
//

@implementation GTLStoreendpointDISCOUNT
@dynamic amount, desc, value;
@end
