/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointGETCHECKDETAILS.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointGETCHECKDETAILS (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointGETCHECKDETAILS.h"

#import "GTLStoreendpointCHECK.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointGETCHECKDETAILS
//

@implementation GTLStoreendpointGETCHECKDETAILS
@dynamic check, intcheckid;
@end
