/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreChatMemberArray.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreChatMemberArray (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreChatMemberArray.h"

#import "GTLStoreendpointStoreChatTeam.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreChatMemberArray
//

@implementation GTLStoreendpointStoreChatMemberArray
@dynamic storeChatMembers;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreChatTeam class]
                                forKey:@"storeChatMembers"];
  return map;
}

@end
