/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointENTRIES.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointENTRIES (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointENTRIES.h"

#import "GTLStoreendpointENTRY.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointENTRIES
//

@implementation GTLStoreendpointENTRIES
@dynamic entry;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointENTRY class]
                                forKey:@"entry"];
  return map;
}

@end
