/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreOrderCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreOrderCollection (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointStoreOrderCollection.h"

#import "GTLStoreendpointStoreOrder.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreOrderCollection
//

@implementation GTLStoreendpointStoreOrderCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointStoreOrder class]
                                forKey:@"items"];
  return map;
}

@end
