/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointDISCOUNTS.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointDISCOUNTS (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointDISCOUNTS.h"

#import "GTLStoreendpointDISCOUNT.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointDISCOUNTS
//

@implementation GTLStoreendpointDISCOUNTS
@dynamic discount;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointDISCOUNT class]
                                forKey:@"discount"];
  return map;
}

@end
