/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreStats.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreStats (0 custom class methods, 10 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreStats
//

@interface GTLStoreendpointStoreStats : GTLObject
@property (retain) NSNumber *createdDate;  // longLongValue
@property (retain) NSNumber *daysOfService;  // intValue
@property (retain) NSNumber *dislikes;  // longLongValue
@property (retain) NSNumber *lastOrderPlacedDate;  // longLongValue
@property (retain) NSNumber *likes;  // longLongValue
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (retain) NSNumber *orders;  // longLongValue
@property (retain) NSNumber *recommendations;  // longLongValue
@property (retain) NSNumber *storeId;  // longLongValue
@property (retain) NSNumber *visits;  // longLongValue
@end
