/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointStoreAndStats.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointStoreAndStats (0 custom class methods, 2 custom properties)

#import "GTLStoreendpointStoreAndStats.h"

#import "GTLStoreendpointStore.h"
#import "GTLStoreendpointStoreStats.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointStoreAndStats
//

@implementation GTLStoreendpointStoreAndStats
@dynamic stats, store;
@end
