/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointChatUserArray.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointChatUserArray (0 custom class methods, 1 custom properties)

#import "GTLStoreendpointChatUserArray.h"

#import "GTLStoreendpointChatUser.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointChatUserArray
//

@implementation GTLStoreendpointChatUserArray
@dynamic chatUsers;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLStoreendpointChatUser class]
                                forKey:@"chatUsers"];
  return map;
}

@end
