/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLStoreendpointCHECK.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   storeendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLStoreendpointCHECK (0 custom class methods, 12 custom properties)

#import "GTLStoreendpointCHECK.h"

#import "GTLStoreendpointDISCOUNTS.h"
#import "GTLStoreendpointENTRIES.h"

// ----------------------------------------------------------------------------
//
//   GTLStoreendpointCHECK
//

@implementation GTLStoreendpointCHECK
@dynamic completetotal, discounts, employee, employeecheckname, entries,
         guestcount, identifier, payments, servicecharges, subtotal,
         tablenumber, tax;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
