/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API

#import "GTLUserendpointConstants.h"

#import "GTLUserendpointUser.h"
#import "GTLUserendpointUserAddress.h"
#import "GTLUserendpointUserAddressCollection.h"
#import "GTLUserendpointUserCard.h"
#import "GTLUserendpointUserCardCollection.h"

#import "GTLQueryUserendpoint.h"
#import "GTLServiceUserendpoint.h"
