/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserendpointUser.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUser (0 custom class methods, 16 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUser
//

@interface GTLUserendpointUser : GTLObject
@property (retain) NSNumber *admin;  // boolValue
@property (copy) NSString *authToken;
@property (retain) NSNumber *createdDate;  // longLongValue
@property (retain) NSNumber *defaultTip;  // longLongValue
@property (copy) NSString *email;
@property (copy) NSString *firstName;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *lastName;
@property (retain) NSNumber *modifiedDate;  // longLongValue
@property (copy) NSString *parseAuthData;
@property (copy) NSString *parseCreatedAt;
@property (copy) NSString *parseObjectId;
@property (copy) NSString *parseUpdatedAt;
@property (copy) NSString *phone;
@property (copy) NSString *profilePhotoUrl;
@property (copy) NSString *userId;
@end
