/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointUserAddress.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUserAddress (0 custom class methods, 13 custom properties)

#import "GTLUserendpointUserAddress.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUserAddress
//

@implementation GTLUserendpointUserAddress
@dynamic address2, address3, city, crossStreet, defaultProperty, identifier,
         lat, lng, state, streetAddress, title, userId, zip;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"default", @"defaultProperty",
      @"id", @"identifier",
      nil];
  return map;
}

@end
