/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointUserAddress.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUserAddress (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUserAddress
//

@interface GTLUserendpointUserAddress : GTLObject
@property (copy) NSString *address1;
@property (copy) NSString *address2;
@property (copy) NSString *address3;
@property (copy) NSString *city;
@property (copy) NSString *crossStreet;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *state;
@property (retain) NSNumber *userId;  // longLongValue
@property (copy) NSString *zip;
@end
