/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserendpointUserAddress.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUserAddress (0 custom class methods, 20 custom properties)

#import "GTLUserendpointUserAddress.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUserAddress
//

@implementation GTLUserendpointUserAddress
@dynamic apartment, city, country, county, crossStreet, defaultProperty,
         fullAddress, identifier, isocountryCode, lat, lng, name, neighbourhood,
         notes, state, street, streetNumber, title, userId, zip;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"default", @"defaultProperty",
      @"id", @"identifier",
      nil];
  return map;
}

@end
