/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointUserCardCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUserCardCollection (0 custom class methods, 1 custom properties)

#import "GTLUserendpointUserCardCollection.h"

#import "GTLUserendpointUserCard.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUserCardCollection
//

@implementation GTLUserendpointUserCardCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLUserendpointUserCard class]
                                forKey:@"items"];
  return map;
}

@end
