/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointUserCard.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUserCard (0 custom class methods, 22 custom properties)

#import "GTLUserendpointUserCard.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUserCard
//

@implementation GTLUserendpointUserCard
@dynamic accessToken, address, brand, cardId, city, country, createdDate,
         defaultProperty, expMonth, expYear, fingerprint, fundingType,
         identifier, last4, modifiedDate, name, provider, providerCustomerId,
         refreshToken, state, userId, zip;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"default", @"defaultProperty",
      @"exp_month", @"expMonth",
      @"exp_year", @"expYear",
      @"id", @"identifier",
      nil];
  return map;
}

@end
