/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLUserendpointUserAddressCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLUserendpointUserAddressCollection (0 custom class methods, 1 custom properties)

#import "GTLUserendpointUserAddressCollection.h"

#import "GTLUserendpointUserAddress.h"

// ----------------------------------------------------------------------------
//
//   GTLUserendpointUserAddressCollection
//

@implementation GTLUserendpointUserAddressCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLUserendpointUserAddress class]
                                forKey:@"items"];
  return map;
}

@end
